name       : qqwing
version    : 1.3.4
release    : 1
source     :
    - https://github.com/stephenostermiller/qqwing/archive/v1.3.4.tar.gz : dc5d61b4470862b190d437f8143d4090639c164d34461c4caa5c081c5c91e6cc
license    : GPL-2.0
component  : programming
summary    : QQwing is software for generating and solving Sudoku puzzles
description: |
    QQwing is software for generating and solving Sudoku puzzles.
libsplit   : no
setup      : |
    sed -i "s/root/dd/" build/not_root_check.sh
install    : |
    %make_install
    install -D -m 00755 /usr/local/bin/qqwing $installdir/usr/bin/qqwing
    install -D -m 00644 /usr/local/include/qqwing.hpp $installdir/usr/include/qqwing.hpp
    install -D -m 00644 /usr/local/lib/pkgconfig/qqwing.pc $installdir/usr/lib64/pkgconfig/qqwing.pc
    cp /usr/local/lib/libqqwing.so* $installdir/usr/lib64/
    chmod 00644 $installdir/usr/lib64/*
    install -D -m 00644 /usr/local/share/man/man1/qqwing.1 $installdir/usr/share/man/man1/qqwing.1
    sed -i "s|/usr/local|/usr|" $installdir/usr/lib64/pkgconfig/qqwing.pc